services:
  postgres:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: marshell
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:8.10.2-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
