//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "permissions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "permissions_name_guard_name_unique")]
    pub name: String,
    #[sea_orm(unique_key = "permissions_name_guard_name_unique")]
    pub guard_name: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many, via = "roles_permissions")]
    pub roles: HasMany<super::roles::Entity>,
    #[sea_orm(has_many, via = "users_permissions")]
    pub users: HasMany<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
