//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "project_tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_project_tag_unique")]
    pub project_id: i64,
    #[sea_orm(unique_key = "idx_project_tag_unique")]
    pub tag_id: i64,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub projects: BelongsTo<super::projects::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tag_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub tags: BelongsTo<super::tags::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
