//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub icon: Option<String>,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(unique)]
    pub slug: String,
    pub color: String,
    pub description: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub posts_tags: HasMany<super::posts_tags::Entity>,
    #[sea_orm(has_many)]
    pub projects_tags: HasMany<super::projects_tags::Entity>,
    #[sea_orm(has_many, via = "projects_tags")]
    pub projects: HasMany<super::projects::Entity>,
    #[sea_orm(has_many, via = "posts_tags")]
    pub posts: HasMany<super::posts::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
