//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod comments;
pub mod likes;
pub mod model_has_permissions;
pub mod model_has_roles;
pub mod permissions;
pub mod post_tag;
pub mod posts;
pub mod project_tag;
pub mod projects;
pub mod role_has_permissions;
pub mod roles;
pub mod shares;
pub mod tags;
pub mod users;
