//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod comments;
pub mod likes;
pub mod permissions;
pub mod posts;
pub mod posts_tags;
pub mod projects;
pub mod projects_tags;
pub mod roles;
pub mod roles_permissions;
pub mod shares;
pub mod tags;
pub mod users;
pub mod users_permissions;
pub mod users_roles;
