//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "model_has_roles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub model_type: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub model_id: i64,
    #[sea_orm(
        belongs_to,
        from = "role_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub roles: BelongsTo<super::roles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
