//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::comments::Entity as Comments;
pub use super::likes::Entity as Likes;
pub use super::model_has_permissions::Entity as ModelHasPermissions;
pub use super::model_has_roles::Entity as ModelHasRoles;
pub use super::permissions::Entity as Permissions;
pub use super::post_tag::Entity as PostTag;
pub use super::posts::Entity as Posts;
pub use super::project_tag::Entity as ProjectTag;
pub use super::projects::Entity as Projects;
pub use super::role_has_permissions::Entity as RoleHasPermissions;
pub use super::roles::Entity as Roles;
pub use super::shares::Entity as Shares;
pub use super::tags::Entity as Tags;
pub use super::users::Entity as Users;
