//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "projects")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub cover_image: Option<String>,
    #[sea_orm(unique)]
    pub title: String,
    #[sea_orm(unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub excerpt: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub estimated_cost: i64,
    pub reading_time: i64,
    pub views_count: i64,
    pub is_pinned: bool,
    pub published_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::project_tag::Entity")]
    ProjectTag,
}

impl Related<super::project_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectTag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
