//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "roles_name_guard_name_unique")]
    pub name: String,
    #[sea_orm(unique_key = "roles_name_guard_name_unique")]
    pub guard_name: String,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::model_has_roles::Entity")]
    ModelHasRoles,
    #[sea_orm(has_many = "super::role_has_permissions::Entity")]
    RoleHasPermissions,
}

impl Related<super::model_has_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModelHasRoles.def()
    }
}

impl Related<super::role_has_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoleHasPermissions.def()
    }
}

impl Related<super::permissions::Entity> for Entity {
    fn to() -> RelationDef {
        super::role_has_permissions::Relation::Permissions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::role_has_permissions::Relation::Roles.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
