//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "roles_name_guard_name_unique")]
    pub name: String,
    #[sea_orm(unique_key = "roles_name_guard_name_unique")]
    pub guard_name: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub model_has_roles: HasMany<super::model_has_roles::Entity>,
    #[sea_orm(has_many, via = "role_has_permissions")]
    pub permissions: HasMany<super::permissions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
