//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub icon: Option<String>,
    pub name: String,
    pub slug: String,
    pub color: String,
    pub description: String,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::taggables::Entity")]
    Taggables,
}

impl Related<super::taggables::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Taggables.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
